# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test

on:
  push:

permissions:
  contents: read


env:
  UV_SYSTEM_PYTHON: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade uv
        uv pip install -r pyproject.toml
    - name: Lint with ruff
      run: |
        ruff check
    - name: Test with pytest
      run: |
        pytest
