name: Test

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t test-image .

    - name: Run ruff linter
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/app \
          -w /app \
          test-image \
          ruff check

    - name: Run pytest
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/app \
          -w /app \
          test-image \
          pytest